/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.josh.numberboard;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Josh
 */
public class BoardsMenu extends javax.swing.JFrame {

    /**
     * Creates new form BoardsMenu
     */
    public BoardsMenu() {
        initComponents();
        
        setImageLabel(fontLabel, "src/main/java/com/josh/resources/Skywallpaper.png");
    }
    
    private void setImageLabel(JLabel label, String imageRute){
        ImageIcon font = new ImageIcon(imageRute);
        Icon image = new ImageIcon(font.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(image);
        this.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fontPanel = new javax.swing.JPanel();
        DeleteBoard = new javax.swing.JButton();
        createBoard = new javax.swing.JButton();
        OpenBoard = new javax.swing.JButton();
        ScrollListBoard = new javax.swing.JScrollPane();
        ListBoard = new javax.swing.JList<>();
        fontLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 420));

        fontPanel.setMinimumSize(new java.awt.Dimension(640, 420));
        fontPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeleteBoard.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DeleteBoard.setText("Eliminar Tablonario");
        DeleteBoard.setEnabled(false);
        fontPanel.add(DeleteBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 170, 40));

        createBoard.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        createBoard.setText("Nuevo Tablonario");
        createBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBoardActionPerformed(evt);
            }
        });
        fontPanel.add(createBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 170, 40));

        OpenBoard.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OpenBoard.setText("Abrir Tablonario");
        OpenBoard.setActionCommand("Abrir Tablonario");
        OpenBoard.setEnabled(false);
        fontPanel.add(OpenBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 170, 40));

        ListBoard.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ListBoard.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "tablonario 1", "tablonario 2", "tablonario 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListBoard.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        ListBoard.setOpaque(false);
        ListBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListBoardMouseClicked(evt);
            }
        });
        ScrollListBoard.setViewportView(ListBoard);

        fontPanel.add(ScrollListBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 340));
        fontPanel.add(fontLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBoardActionPerformed
        newBoard.setLocationRelativeTo(null);
        newBoard.setVisible(true);
    }//GEN-LAST:event_createBoardActionPerformed

    private void ListBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListBoardMouseClicked
        if(ListBoard.getSelectedIndex() != -1){
            OpenBoard.setEnabled(true);
            DeleteBoard.setEnabled(true);
        }
    }//GEN-LAST:event_ListBoardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBoard;
    private javax.swing.JList<String> ListBoard;
    private javax.swing.JButton OpenBoard;
    private javax.swing.JScrollPane ScrollListBoard;
    private javax.swing.JButton createBoard;
    private javax.swing.JLabel fontLabel;
    private javax.swing.JPanel fontPanel;
    // End of variables declaration//GEN-END:variables

    private AddBoard newBoard = new AddBoard();
}
